version: 2.1

executors:
  system:
    machine:
      image: ubuntu-1604:202004-01

commands:
  run_docker_target:
    parameters:
      target:
        type: string
    steps:
      - checkout
      - run:
          command: |
            export DOCKER_BUILDKIT=1
            docker build . --target <<parameters.target>>

jobs:
  analyze:
    executor: system
    steps:
      - checkout
      - run_docker_target:
          target: analyze

  test:
    executor: system
    steps:
      - checkout
      - run_docker_target:
          target: test

  build:
    executor: system
    steps:
      - checkout
      - run_docker_target:
          target: build

workflows:
  make:
    jobs:
      - analyze
      - test
      - build
