version: 2.1

executors:
  node:
    docker:
      - image: node:17.3.0

jobs:
  analyze:
    executor: node
    steps:
      - checkout
      - run: 'yarn install'
      - run: 'yarn lint'
  test:
    executor: node
    steps:
      - checkout
      - run: 'yarn install'
      - run: 'yarn test'
      - store_artifacts:
          path: reports/coverage
      - store_test_results:
          path: reports/results/junit.xml
  build:
    executor: node
    steps:
      - checkout
      - run: 'yarn install'
      - run: 'yarn build'

workflows:
  make:
    jobs:
      - analyze
      - test
      - build
