# Copyright 2020 Anthony Bonta
apiVersion: v1
kind: Namespace
metadata:
  name: zthunworks

---
apiVersion: v1
kind: Secret
metadata:
  name: zthunworks-secrets-db-urls
  namespace: zthunworks
type: Opaque
stringData:
  database-vault-url: ${database-vault-url}
  database-users-url: ${database-users-url}

---
apiVersion: v1
kind: Secret
metadata:
  name: zthunworks-secrets-certs
  namespace: zthunworks
type: Opaque
data:
  zthunworks.com.crt: ${zthunworks.com.crt}
  zthunworks.com.key: ${zthunworks.com.key}

---
apiVersion: v1
kind: Service
metadata:
  name: zthunworks-services-client
  namespace: zthunworks
spec:
  type: ClusterIP
  selector:
    app: zthunworks-pods-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zthunworks-deployments-client
  namespace: zthunworks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zthunworks-pods-client
  template:
    metadata:
      name: zthunworks-pods-client
      labels:
        app: zthunworks-pods-client
        version: 1.0.0-9
    spec:
      containers:
        - name: zthunworks-pods-client
          image: zthun/works.client:1.0.0-9
          ports:
            - containerPort: 443
              hostPort: 443
            - containerPort: 80
              hostPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: zthunworks-services-server
  namespace: zthunworks
spec:
  type: ClusterIP
  selector:
    app: zthunworks-pods-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zthunworks-deployments-server
  namespace: zthunworks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zthunworks-pods-server
  template:
    metadata:
      name: zthunworks-pods-server
      labels:
        app: zthunworks-pods-server
        version: 1.0.0-9
    spec:
      containers:
        - name: zthunworks-pods-server
          image: zthun/works.server:1.0.0-9
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_VAULT_URL
              valueFrom:
                secretKeyRef:
                  name: zthunworks-secrets-db-urls
                  key: database-vault-url
            - name: DATABASE_USERS_URL
              valueFrom:
                secretKeyRef:
                  name: zthunworks-secrets-db-urls
                  key: database-users-url

---
apiVersion: v1
kind: Service
metadata:
  name: zthunworks-services-proxy
  namespace: zthunworks
spec:
  type: LoadBalancer
  selector:
    app: zthunworks-pods-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: 'http'
    - protocol: TCP
      port: 443
      targetPort: 443
      name: 'https'

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zthunworks-deployments-proxy
  namespace: zthunworks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zthunworks-pods-proxy
  template:
    metadata:
      name: zthunworks-pods-proxy
      labels:
        app: zthunworks-pods-proxy
        version: 1.0.0
    spec:
      containers:
        - name: zthunworks-pods-proxy
          image: zthun/works.proxy:1.0.0-9
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/certs
              name: zthunworks-pods-proxy-volumes-certs
              readOnly: true
      volumes:
        - name: zthunworks-pods-proxy-volumes-certs
          secret:
            secretName: zthunworks-secrets-certs
