apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    cert-manager.io/issuer: '{{ .Chart.Name }}-cert-issuer'
spec:
  tls:
    - hosts:
      - {{ .Values.domain }}
      secretName: {{ .Chart.Name }}-tls
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Chart.Name }}-services-client
              servicePort: 80
          - path: /api
            backend:
               serviceName: {{ .Chart.Name }}-services-server
               servicePort: 3000
