apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets-db-urls
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  database-vault-url: {{ .Values.database.vault }}
  database-users-url: {{ .Values.database.users }}
