apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-services-client
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name}}-pods-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
