apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-services-server
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}-pods-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
